// Code generated by protoc-gen-wsrpc. DO NOT EDIT.
// source: example/api/proto.proto
// protoc version: 3.5.1
// protoc-gen-wsrpc version: 0.1.0-dev

package api

import (
	"github.com/Percona-Lab/wsrpc"
	"github.com/golang/protobuf/proto"
	"github.com/pkg/errors"
)

// Client API for api.EchoService service

type EchoServiceClient interface {
	Echo(*EchoRequest) (*EchoResponse, error)
}

type echoServiceClient struct {
	conn *wsrpc.Conn
}

func NewEchoServiceClient(conn *wsrpc.Conn) EchoServiceClient {
	return &echoServiceClient{conn}
}

func (c *echoServiceClient) Echo(req *EchoRequest) (*EchoResponse, error) {
	b, err := proto.Marshal(req)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to marshal protobuf message %T", req)
	}
	if b, err = c.conn.Invoke("Echo", b); err != nil {
		return nil, err
	}
	res := new(EchoResponse)
	if err = proto.Unmarshal(b, res); err != nil {
		return nil, errors.Wrapf(err, "failed to unmarshal protobuf message to %T", res)
	}
	return res, nil
}

// check interface
var _ EchoServiceClient = (*echoServiceClient)(nil)

// Server API for api.EchoService service

type EchoServiceServer interface {
	Echo(*EchoRequest) (*EchoResponse, error)
}

type EchoServiceDispatcher struct {
	conn   *wsrpc.Conn
	server EchoServiceServer
}

func NewEchoServiceDispatcher(conn *wsrpc.Conn, server EchoServiceServer) *EchoServiceDispatcher {
	return &EchoServiceDispatcher{conn, server}
}

func dispatchEcho(server interface{}, arg []byte) ([]byte, error) {
	req := new(EchoRequest)
	if err := proto.Unmarshal(arg, req); err != nil {
		return nil, errors.Wrapf(err, "failed to unmarshal protobuf message to %T", req)
	}
	res, err := server.(EchoServiceServer).Echo(req)
	if err != nil {
		return nil, err
	}
	b, err := proto.Marshal(res)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to marshal protobuf message %T", res)
	}
	return b, nil
}

var echoServiceDescription = &wsrpc.ServiceDesc{
	Methods: []wsrpc.ServiceMethod{
		{
			Name:   "Echo",
			Method: dispatchEcho,
		},
	},
}

func (d *EchoServiceDispatcher) Run() (exitErr error) {
	for {
		message, err := d.conn.Read()
		if err != nil {
			exitErr = errors.Wrap(err, "failed to read message")
			return
		}

		var found bool
		for _, method := range echoServiceDescription.Methods {
			if method.Name != message.Path {
				continue
			}

			res, err := method.Method(d.server, message.Arg)
			if err != nil {
				exitErr = errors.Wrapf(err, "%s returned error", method.Name)
				return
			}

			message = &wsrpc.Message{
				StreamID: message.StreamID,
				Path:     message.Path,
				Arg:      res,
			}
			if err = d.conn.Write(message); err != nil {
				// TODO close stream, not not the whole connection
				exitErr = errors.Wrap(err, "failed to write message")
				return
			}

			found = true
			break
		}

		if !found {
			exitErr = errors.Wrapf(err, "unexpected path %q", message.Path)
			return
		}
	}
}
