// +build ignore

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/api/proto.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	example/api/proto.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
	PowRequest
	PowResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type EchoResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PowRequest struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *PowRequest) Reset()                    { *m = PowRequest{} }
func (m *PowRequest) String() string            { return proto.CompactTextString(m) }
func (*PowRequest) ProtoMessage()               {}
func (*PowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PowRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PowRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PowResponse struct {
	Pow float64 `protobuf:"fixed64,1,opt,name=pow" json:"pow,omitempty"`
}

func (m *PowResponse) Reset()                    { *m = PowResponse{} }
func (m *PowResponse) String() string            { return proto.CompactTextString(m) }
func (*PowResponse) ProtoMessage()               {}
func (*PowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PowResponse) GetPow() float64 {
	if m != nil {
		return m.Pow
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "api.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "api.EchoResponse")
	proto.RegisterType((*PowRequest)(nil), "api.PowRequest")
	proto.RegisterType((*PowResponse)(nil), "api.PowResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoService service

type EchoServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/api.EchoService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoService service

type EchoServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/proto.proto",
}

// Client API for PowService service

type PowServiceClient interface {
	Pow(ctx context.Context, in *PowRequest, opts ...grpc.CallOption) (*PowResponse, error)
}

type powServiceClient struct {
	cc *grpc.ClientConn
}

func NewPowServiceClient(cc *grpc.ClientConn) PowServiceClient {
	return &powServiceClient{cc}
}

func (c *powServiceClient) Pow(ctx context.Context, in *PowRequest, opts ...grpc.CallOption) (*PowResponse, error) {
	out := new(PowResponse)
	err := grpc.Invoke(ctx, "/api.PowService/Pow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PowService service

type PowServiceServer interface {
	Pow(context.Context, *PowRequest) (*PowResponse, error)
}

func RegisterPowServiceServer(s *grpc.Server, srv PowServiceServer) {
	s.RegisterService(&_PowService_serviceDesc, srv)
}

func _PowService_Pow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowServiceServer).Pow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PowService/Pow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowServiceServer).Pow(ctx, req.(*PowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PowService",
	HandlerType: (*PowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pow",
			Handler:    _PowService_Pow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/proto.proto",
}

func init() { proto.RegisterFile("example/api/proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x85, 0xd9, 0x94, 0xa0, 0x51, 0xc8, 0xf6, 0x92, 0x78, 0xa9, 0xf6, 0x24, 0x04, 0x0a, 0x06,
	0x1d, 0xba, 0x77, 0x17, 0xfb, 0x05, 0x9b, 0x2d, 0xb4, 0x50, 0xed, 0xa6, 0x96, 0xfa, 0xef, 0xc3,
	0x59, 0x45, 0x0f, 0x5d, 0x96, 0x79, 0xb3, 0xdf, 0x7b, 0x3c, 0x06, 0xd6, 0xa2, 0xe1, 0x4f, 0xfd,
	0x10, 0x31, 0xd7, 0x32, 0xd6, 0x85, 0xaa, 0x54, 0x84, 0x2f, 0xb5, 0xb8, 0x96, 0x6c, 0x07, 0xce,
	0x39, 0xbf, 0xab, 0x4c, 0xbc, 0x3f, 0xa2, 0xac, 0x28, 0x05, 0xfb, 0xc6, 0x2b, 0xee, 0x93, 0x2d,
	0x09, 0x17, 0x19, 0xce, 0x8c, 0x81, 0x6b, 0x90, 0x52, 0xab, 0x57, 0x29, 0xfe, 0x32, 0x21, 0x40,
	0xaa, 0xea, 0x21, 0xc5, 0x05, 0xd2, 0xe0, 0x37, 0xc9, 0x48, 0xd3, 0xa9, 0xd6, 0x9f, 0x19, 0xd5,
	0xb2, 0x0d, 0x38, 0x48, 0xf6, 0x61, 0x1e, 0x58, 0x5a, 0xd5, 0x3d, 0xdc, 0x8d, 0xc9, 0xc9, 0x34,
	0xba, 0x88, 0xe2, 0x2b, 0x73, 0x41, 0xf7, 0x60, 0x77, 0x92, 0x7a, 0x11, 0xd7, 0x32, 0x9a, 0x74,
	0x0d, 0x56, 0x93, 0x8d, 0x49, 0x4b, 0x8e, 0x58, 0x63, 0xb0, 0x86, 0x60, 0xa5, 0xaa, 0xa6, 0x4b,
	0xe4, 0xc6, 0x7a, 0x81, 0x37, 0x2e, 0x8c, 0xef, 0x3a, 0xc7, 0x8b, 0x1c, 0x7e, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0xc6, 0xdb, 0x00, 0x2c, 0x01, 0x00, 0x00,
}
