// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/api/proto.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	example/api/proto.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
	EmptyRequest
	EmptyResponse
	PowRequest
	PowResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type EchoResponse struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PowRequest struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *PowRequest) Reset()                    { *m = PowRequest{} }
func (m *PowRequest) String() string            { return proto.CompactTextString(m) }
func (*PowRequest) ProtoMessage()               {}
func (*PowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PowRequest) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PowRequest) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PowResponse struct {
	Pow float64 `protobuf:"fixed64,1,opt,name=pow" json:"pow,omitempty"`
}

func (m *PowResponse) Reset()                    { *m = PowResponse{} }
func (m *PowResponse) String() string            { return proto.CompactTextString(m) }
func (*PowResponse) ProtoMessage()               {}
func (*PowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PowResponse) GetPow() float64 {
	if m != nil {
		return m.Pow
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "api.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "api.EchoResponse")
	proto.RegisterType((*EmptyRequest)(nil), "api.EmptyRequest")
	proto.RegisterType((*EmptyResponse)(nil), "api.EmptyResponse")
	proto.RegisterType((*PowRequest)(nil), "api.PowRequest")
	proto.RegisterType((*PowResponse)(nil), "api.PowResponse")
}

func init() { proto.RegisterFile("example/api/proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0x5d, 0x05, 0x67, 0xab, 0x5b, 0xe7, 0xe2, 0xd2, 0x8b, 0x9a, 0x53, 0x41, 0xc8,
	0xc2, 0x0a, 0xbe, 0xc1, 0xde, 0x97, 0xfa, 0x04, 0x71, 0x0d, 0x18, 0xb1, 0x66, 0x6c, 0xa3, 0x6d,
	0xdf, 0x5e, 0x3a, 0x49, 0x69, 0x0e, 0x5e, 0xca, 0xfc, 0xd3, 0x6f, 0xe6, 0xff, 0x27, 0x70, 0x6b,
	0x06, 0xdd, 0xd0, 0xa7, 0xd9, 0x69, 0xb2, 0x3b, 0x6a, 0x9d, 0x77, 0x8a, 0xbf, 0x98, 0x69, 0xb2,
	0xf2, 0x01, 0xd6, 0x87, 0xd3, 0xbb, 0xab, 0xcd, 0xf7, 0x8f, 0xe9, 0x3c, 0x22, 0xac, 0xde, 0xb4,
	0xd7, 0x5b, 0x71, 0x2f, 0xaa, 0xcb, 0x9a, 0x6b, 0x29, 0x21, 0x0f, 0x48, 0x47, 0xee, 0xab, 0x33,
	0xff, 0x32, 0xd7, 0x90, 0x1f, 0x1a, 0xf2, 0x63, 0xdc, 0x23, 0x37, 0x70, 0x15, 0x75, 0x18, 0x92,
	0x15, 0xc0, 0xd1, 0xf5, 0xb3, 0x4d, 0x0e, 0x62, 0xe0, 0x79, 0x51, 0x8b, 0x61, 0x52, 0xe3, 0xf6,
	0x2c, 0xa8, 0x51, 0xde, 0xc1, 0x9a, 0xc9, 0xe8, 0x56, 0x40, 0x46, 0xae, 0x8f, 0xf0, 0x54, 0xee,
	0x3f, 0x42, 0xe4, 0x17, 0xd3, 0xfe, 0xda, 0x93, 0xc1, 0x47, 0x58, 0x4d, 0x12, 0x0b, 0xa5, 0xc9,
	0xaa, 0xe4, 0x98, 0xf2, 0x26, 0xe9, 0xc4, 0x6d, 0x0a, 0xce, 0x39, 0x17, 0xc6, 0x7f, 0x49, 0xe6,
	0x12, 0xd3, 0x56, 0xe0, 0xf7, 0xcf, 0x1c, 0x7b, 0xb6, 0xaa, 0x20, 0x3b, 0xba, 0x1e, 0x37, 0x0c,
	0x2e, 0xe7, 0x94, 0xc5, 0xd2, 0x08, 0x73, 0xaf, 0x17, 0xfc, 0xc4, 0x4f, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0xba, 0x1b, 0x3f, 0x7d, 0x01, 0x00, 0x00,
}
